### PR TITLE
Build update

### PR DESCRIPTION
**Pull request by sisbell**
Issues fixed:
#17 cleanup mess with jtorctl-briar.jar
#18 Build Android Tor (this is no longer needed since we are dependent of tor-android-library for this)
#19 Debugging data
#30: Could not find proxy universal library
#35: x86 build for Tor Binary
#38: Problem installing gradle

Build changes
Updated Gradle to 4.5 across project
Updated Android Gradle build to 3.0.1
Require JDK version 1.7
Require Android SDK Version 21+
Include tor-android-library for Android install
Include jtorctl:02 binary library (deleted jtorctl-briar lib)

Code Changes
OnionProxyManager allows an implementing class to decide how to setup Tor. 
Moved java specific Tor install code from universal to java module.
Use tor-android-library for Tor install in android module
Some signature changes related to latest jtorctl import
Added parameter to allow logging of tor control processing

Todos:
Tested on Mac and Android device. Still needs testing on linux/windows/android_emulator
Unit tests
The threading logic in existing code should move to a publish/subscribe pattern.
Need to maintain different versions of Tor binaries per platform version. Currently project is only using latest version which isn’t good for backwards compatibility.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/tor_onion_proxy_library/45)

### CODE REVIEW

**Comment by yaronyg** [comment]
Thank you so much for this! I just had one minor question and then we can commit. Thanks!

---

Reviewed 48 of 48 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[universal/src/main/java/com/msopentech/thali/toronionproxy/OnionProxyContext.java, line 61 at r1](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45#-L4c9pBR76er1GcrTW8I:-L4c9pBT7jpTjYmKE7lr:bjnzlg3) ([raw file](https://github.com/thaliproject/tor_onion_proxy_library/blob/876b8fc5255e55725151a0797efc347aa8fe7210/universal/src/main/java/com/msopentech/thali/toronionproxy/OnionProxyContext.java#L61)):*
> ```Java
>     }
> 
>     public final File getGeoIpv6File() {
> ```

Why does this need to be final?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45#-:-L4cAYC7e6dtae7tD6jd:bxg7xb9)*

**Comment by sisbell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[universal/src/main/java/com/msopentech/thali/toronionproxy/OnionProxyContext.java, line 61 at r1](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45#-L4c9pBR76er1GcrTW8I:-L4cNFqvL1WoMqnrjOIE:b-fq22m3) ([raw file](https://github.com/thaliproject/tor_onion_proxy_library/blob/876b8fc5255e55725151a0797efc347aa8fe7210/universal/src/main/java/com/msopentech/thali/toronionproxy/OnionProxyContext.java#L61)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why does this need to be final?
</blockquote></details>

I was inferring the intent from the original code, where the fields are final. So it would make sense that the method accessors for those fields should also be final. 

I could see the case where we would want some configuration file not to be in the working directory. There are couple of solutions that jump out.

1) Marking these method accessors as not final. I would suggest in that case to also remove the final flag on the respective fields so they could be overriden in the subclass.

2) Create a ConfigBuilder class that allows the application to specialize config locations. Then we would have: OnionProxyContext(ConfigBuilder builder). The default builder would be WorkingDirConfigBuilder(File dir)

I’m more in favor of (2), not much work either way. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45)*

**Comment by sisbell** [comment]
I was inferring the intent from the original code, where the fields are final. So it would make sense that the method accessors for those fields should also be final. 

I could see the case where we would want some configuration file not to be in the working directory. There are couple of solutions that jump out.

1) Marking these method accessors as not final. I would suggest in that case to also remove the final flag on the respective fields so they could be overriden in the subclass.

2) Create a ConfigBuilder class that allows the application to specialize config locations. Then we would have: OnionProxyContext(ConfigBuilder builder). The default builder would be WorkingDirConfigBuilder(File dir)

I’m more in favor of (2), not much work either way. Thoughts?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45#-:-L4cNjNvBSLI5EROYAky:b-fq22m3)*

**Comment by yaronyg** [comment]
2 sounds great, thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45#-:-L4lMgJT924ZzaxlhqUP:bq0dp7k)*

**Comment by sisbell** [comment]
Should have the ConfigBuilder complete and ready for review by 2/10

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45#-:-L4r9--JM08PxSylKl5j:bases63)*

**Comment by yaronyg** [comment]
Looking forward to it!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/tor_onion_proxy_library/45#-:-L4rCVUFMuu2txcsA3su:bevun1q)*

**Comment by sisbell** [comment]
Ready for review and commit. 

General:
* TorConfig/TorConfig.Builder - makes easy to configure Tor for different environments or to use existing platform installations 
* TorInstaller - abstracted out installer code into its own class [Java/Android]
* Improved logging
* Improved concurrency handling on files

Android:
* Add sl4j android logging library so logs will display

**Comment by yaronyg** [comment]
This is great! I'm happy to ignore my last comment and commit if you would like since the comment is about an issue that predates your code. Just let me know. Thanks!

---

Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[universal/src/main/java/com/msopentech/thali/toronionproxy/FileUtilities.java, line 83 at r2](https://beta.reviewable.io/reviews/thaliproject/tor_onion_proxy_library/45#-L5A9n347uJVuAZvs3UF:-L5A9n354EHMMdNXcVZv:bx3eto6) ([raw file](https://github.com/thaliproject/tor_onion_proxy_library/blob/0ebdd33a287a5d7b10f40a0bea7bcec7d76d257f/universal/src/main/java/com/msopentech/thali/toronionproxy/FileUtilities.java#L83)):*
> ```Java
> 
>     public static boolean setToReadOnlyPermissions(File file) {
>         return file.setReadable(false, false) &&
> ```

I believe this is actually code that you just moved here but doesn't it look wrong? Why we are setting writable and executable to true for a function that says it is setting read only permissions? And no, I don't remember. :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/thaliproject/tor_onion_proxy_library/45#-:-L5AD0wp7MamXLf-p_07:b-psacv2)*

**Comment by sisbell** [comment]
> .
The FileUtilities.setToReadOnlyPermissions is correct behavior. It's not clear from Javadocs for the File class, but the first three lines remove all permissions (user/world/group). Then last three set them to user only. Without first three lines, the last three would leave group permissions on top of current file permissions (probably only a *nix issue).

    public static boolean setToReadOnlyPermissions(File file) {
        return file.setReadable(false, false) &&
                file.setWritable(false, false) &&
                file.setExecutable(false, false) &&

                file.setReadable(true, true) &&
                file.setWritable(true, true) &&
                file.setExecutable(true, true);
    }
If everything else looks good, I'd say its ready for a merge from my side.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/thaliproject/tor_onion_proxy_library/45#-:-L5AMvVN62s0RVYtyZDv:b-q7lke0)*

**Pull request merged**
